"""v1 tables

Revision ID: 02bec7042a4f
Revises: 
Create Date: 2025-12-25 13:57:18.255794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02bec7042a4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('clients', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('clients', 'api_key_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.drop_column('clients', 'rate_limit_per_min')
    op.drop_column('clients', 'is_active')
    op.add_column('market_snapshots', sa.Column('source', sa.String(length=100), nullable=False))
    op.add_column('market_snapshots', sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('market_snapshots', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('market_snapshots', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.drop_constraint(op.f('market_snapshots_city_district_deal_type_market_type_rooms__key'), 'market_snapshots', type_='unique')
    op.drop_column('market_snapshots', 'p25_price_m2')
    op.drop_column('market_snapshots', 'rooms')
    op.drop_column('market_snapshots', 'market_type')
    op.drop_column('market_snapshots', 'p75_price_m2')
    op.drop_column('market_snapshots', 'updated_at')
    op.drop_column('market_snapshots', 'city')
    op.drop_column('market_snapshots', 'district')
    op.drop_column('market_snapshots', 'deal_type')
    op.drop_column('market_snapshots', 'offers_count')
    op.drop_column('market_snapshots', 'p50_price_m2')
    op.drop_column('market_snapshots', 'house_material')
    op.add_column('valuation_requests', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('valuation_requests', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('valuation_requests', 'client_id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(as_uuid=False),
               nullable=False)
    op.drop_constraint(op.f('valuation_requests_client_id_fkey'), 'valuation_requests', type_='foreignkey')
    op.create_foreign_key(None, 'valuation_requests', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('valuation_requests', 'request_id')
    op.add_column('valuation_results', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('valuation_results', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('valuation_results', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.create_unique_constraint(None, 'valuation_results', ['request_id'])
    op.create_foreign_key(None, 'valuation_results', 'valuation_requests', ['request_id'], ['id'], ondelete='CASCADE')
    op.drop_column('valuation_results', 'confidence')
    op.drop_column('valuation_results', 'schema_version')
    op.drop_column('valuation_results', 'meta')
    op.drop_column('valuation_results', 'model_version')
    op.drop_column('valuation_results', 'price_min')
    op.drop_column('valuation_results', 'price_max')
    op.drop_column('valuation_results', 'price_point')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valuation_results', sa.Column('price_point', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('valuation_results', sa.Column('price_max', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('valuation_results', sa.Column('price_min', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('valuation_results', sa.Column('model_version', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('valuation_results', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('valuation_results', sa.Column('schema_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('valuation_results', sa.Column('confidence', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'valuation_results', type_='foreignkey')
    op.drop_constraint(None, 'valuation_results', type_='unique')
    op.alter_column('valuation_results', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('valuation_results', 'details')
    op.drop_column('valuation_results', 'price')
    op.add_column('valuation_requests', sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'valuation_requests', type_='foreignkey')
    op.create_foreign_key(op.f('valuation_requests_client_id_fkey'), 'valuation_requests', 'clients', ['client_id'], ['id'])
    op.alter_column('valuation_requests', 'client_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('valuation_requests', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('valuation_requests', 'status')
    op.add_column('market_snapshots', sa.Column('house_material', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('market_snapshots', sa.Column('p50_price_m2', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('offers_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('deal_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('market_snapshots', sa.Column('district', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('market_snapshots', sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('market_snapshots', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('market_snapshots', sa.Column('p75_price_m2', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('market_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('market_snapshots', sa.Column('rooms', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('market_snapshots', sa.Column('p25_price_m2', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('market_snapshots_city_district_deal_type_market_type_rooms__key'), 'market_snapshots', ['city', 'district', 'deal_type', 'market_type', 'rooms', 'house_material'], postgresql_nulls_not_distinct=False)
    op.alter_column('market_snapshots', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('market_snapshots', 'created_at')
    op.drop_column('market_snapshots', 'snapshot')
    op.drop_column('market_snapshots', 'source')
    op.add_column('clients', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('rate_limit_per_min', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=False))
    op.alter_column('clients', 'api_key_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('clients', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('clients', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
